# Generated by Django 2.1.3 on 2018-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255)),
                ('battery_removable', models.BooleanField(null=True)),
                ('battery_capacity', models.IntegerField(null=True)),
                ('battery_tech', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('cpu', models.CharField(max_length=255)),
                ('cpu_cores', models.CharField(max_length=255)),
                ('current_branch', models.CharField(max_length=255)),
                ('depth_mm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('gpu', models.CharField(max_length=255)),
                ('height_mm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('install_method', models.CharField(max_length=255)),
                ('kernel', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('screen_mm', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('screen_ppi', models.IntegerField(null=True)),
                ('screen_res_x', models.IntegerField(null=True)),
                ('screen_res_y', models.IntegerField(null=True)),
                ('screen_tech', models.CharField(blank=True, max_length=255)),
                ('sdcard', models.CharField(blank=True, max_length=255)),
                ('sdcard_max_gb', models.IntegerField(null=True)),
                ('storage', models.CharField(blank=True, max_length=255)),
                ('tree', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('vendor_short', models.CharField(blank=True, max_length=255)),
                ('width', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('wifi', models.CharField(max_length=255)),
                ('cameras', models.ManyToManyField(to='devices.Camera')),
                ('channels', models.ManyToManyField(to='devices.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=255)),
                ('bands', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RamVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='maintainers',
            field=models.ManyToManyField(to='devices.Maintainer'),
        ),
        migrations.AddField(
            model_name='device',
            name='models',
            field=models.ManyToManyField(to='devices.Model'),
        ),
        migrations.AddField(
            model_name='device',
            name='networks',
            field=models.ManyToManyField(to='devices.Network'),
        ),
        migrations.AddField(
            model_name='device',
            name='peripherals',
            field=models.ManyToManyField(to='devices.Peripheral'),
        ),
        migrations.AddField(
            model_name='device',
            name='ram_variants',
            field=models.ManyToManyField(to='devices.RamVariant'),
        ),
        migrations.AddField(
            model_name='device',
            name='soc_variants',
            field=models.ManyToManyField(to='devices.SocVariant'),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_variants',
            field=models.ManyToManyField(to='devices.StorageVariant'),
        ),
        migrations.AddField(
            model_name='device',
            name='versions',
            field=models.ManyToManyField(to='devices.Version'),
        ),
    ]
