# Generated by Django 2.1.3 on 2018-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20181110_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='depth_mm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='height_mm',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_mm',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
