# Generated by Django 2.1.3 on 2018-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20181110_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='carrier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
