# Generated by Django 2.1.3 on 2018-11-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181110_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='depth_mm',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
