# Generated by Django 2.1.3 on 2018-11-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20181110_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='recovery_boot',
        ),
    ]
