# Generated by Django 2.1.3 on 2018-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_recovery_boot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='ram_variants',
        ),
        migrations.RemoveField(
            model_name='device',
            name='soc_variants',
        ),
        migrations.RemoveField(
            model_name='device',
            name='storage_variants',
        ),
        migrations.AddField(
            model_name='device',
            name='ram_variants',
            field=models.ManyToManyField(to='devices.RamVariant'),
        ),
        migrations.AddField(
            model_name='device',
            name='soc_variants',
            field=models.ManyToManyField(to='devices.SocVariant'),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_variants',
            field=models.ManyToManyField(to='devices.StorageVariant'),
        ),
    ]
